return {}

-- return {
--
--   'nvim-lualine/lualine.nvim',
--   config = function()
--     require('lualine').setup {
--       options = {
--         theme = 'catppuccin', --Use the catpuccin theme for lualine
--         section_separateors = '',
--         component_separators = '',
--         icons_enabled = true,
--       },
--       dependencies = { 'nvim-tree/nvim-web-devicons' },
--       -- you can further customize sections here,
--       sections = {
--         lualine_a = { 'mode' },
--         lualine_b = { 'branch', 'diff', 'diagnostics' },
--         lualine_c = { 'filename' },
--         lualine_x = { 'filetype' },
--         lualine_y = { 'progress' },
--         lualine_z = { 'location' },
--       },
--     }
--   end,
-- }
